services:
  pipeline:
    build: .
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro  # Includes config file
      - ~/.gitconfig:/root/.gitconfig:ro  # Optional: mount global git config
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Reads from host's .env file
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}  # Removed default
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}  # Removed default
    network_mode: "host"  # To access external Ollama
    command: >
      fish -c "
        pip install -e ".[dev]" &&
        fish
      "
    stdin_open: true   # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY
