services:
  pipeline:
    build: .
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Reads from host's .env file
    network_mode: "host"  # To access external Ollama
    command: >
      fish -c "
        pip install -e . &&
        fish
      "
    stdin_open: true   # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY
